import { getSession, signOut } from 'next-auth/react';
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function AccountPage({session}) {

    const router = useRouter();
    
  const [ userEmail, setUserEmail ] = useState('');
  const [ userName, setUserName ] = useState('');
  const handleSignOut = async (e) => {            
    await signOut();    
  }

  
  useEffect(() => {                          
    if(!Boolean(session)) {
       router.push('/login')                                  
    }   
    else {   

    //  setUserEmail(session.user.user.email)
     setUserName(session.user.user.name)
    //  setTokenExpiration(session.expires)
      console.log(session)
    }                
 
 }, [])
 
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome <a href="https://nextjs.org">YOU ARE LOGGED IN AS {userName}</a>
        </h1>
        <button onClick={handleSignOut}>Sign Out</button>
      </main>
 
    </div>
  )
}




export async function getServerSideProps(context) {
    
    return {
      props: {      
        session: await getSession(context)
      },
    };
  }
    